ДЗ "Dagger": Роман Скаскевич
Otus-Android/Homework_04 pull request #142
Opened 2024-09-26 08:41 UTC by romasks

Сделано:

- обновление приложения 
- создание графа DI
- подключение передачи значения между фрагментами через Flow

2024-10-06 09:39 UTC, antonkazakov requested changes
Привет. Оставил пару комментариев

2024-10-06 09:39 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/ActivityScope.kt
> +@Retention(AnnotationRetention.RUNTIME)
Можно убрать. В рантайме аннотации даггера не нужны

2024-10-06 09:39 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/ViewModelReceiver.kt
> +    eventBus: EventBus
EventBus лучше на 2 интерфейса разбить, мутабельный и имутабельный, чтобы нельзя было из ресиверов эмитить

2024-10-29 00:12 UTC, romasks commented on app/src/main/java/ru/otus/daggerhomework/ActivityScope.kt
> +@Retention(AnnotationRetention.RUNTIME)
@antonkazakov Можешь объяснить, почему они в рантайме нам не нужны? Работал с даггером и аннотации помечал рантаймом. Хочу понять нюансы)

2024-11-23 08:37 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/ActivityScope.kt
> +@Retention(AnnotationRetention.RUNTIME)
Привет. Потому что даггер же аннотации процессит на этапе компиляции, конкретно по аннотации скоуп он решит как использовать фабрики, оборачивать ли их в DoubleCheck/SingleCheck, сгенерирует соответствующий код. В рантайме он ничего с ними делать не будет

2025-11-17 13:35 UTC, closed without merging