ДЗ по даггеру
Otus-Android/Homework_04 pull request #34
Opened 2022-03-17 07:53 UTC by quriza

2022-03-19 22:58 UTC, ZadorozhnyiSemen requested changes
Комментарии по ДЗ

2022-03-19 22:58 UTC, ZadorozhnyiSemen commented on app/src/main/java/ru/otus/daggerhomework/App.kt
> +    override fun onCreate() {
onCreate можно убрать, он только делает вызов родителя

2022-03-19 22:58 UTC, ZadorozhnyiSemen commented on app/src/main/java/ru/otus/daggerhomework/FragmentProducer.kt
> +class FragmentProducer @Inject constructor(context:Context,colorGenerator: ColorGenerator,publishSubject: PublishSubject<Int>) : Fragment() {
Тут очень опасный момент, рекомендуется не делать инъекции через конструкторы в Fragment и Activity, потому что андройд может сам позвать их конструткор (он позовет дефолтный) и инъекция не сработает

2022-03-19 22:58 UTC, ZadorozhnyiSemen commented on app/src/main/java/ru/otus/daggerhomework/FragmentReceiver.kt
> +class FragmentReceiver @Inject constructor(application: Application,publishSubject: PublishSubject<Int>) : Fragment() {
то. же самое тут, во фрагменте нужно избегать инъекции через конструктор

2022-03-19 22:58 UTC, ZadorozhnyiSemen commented on app/src/main/java/ru/otus/daggerhomework/FragmentReceiver.kt
> +        viewModel.result.observe(viewLifecycleOwner, colorObserver)
Можно не выносить observer в переменную, если он используется только в одном месте

2022-03-19 22:58 UTC, ZadorozhnyiSemen commented on app/src/main/java/ru/otus/daggerhomework/MainActivity.kt
> +       /* val observer = Observer<ViewModelProducer.Result> { result ->
Можно удалить неиспользуемый код

2022-03-19 22:58 UTC, ZadorozhnyiSemen commented on app/src/main/java/ru/otus/daggerhomework/FragmentReceiver.kt
> +class FragmentReceiver @Inject constructor(application: Application,publishSubject: PublishSubject<Int>) : Fragment() {
попробую сменить ориентацию девайса, будет нагляднее)

2022-03-19 22:58 UTC, ZadorozhnyiSemen commented on app/src/main/java/ru/otus/daggerhomework/MainActivity.kt
> +/*    val appMainActivityComponent: MainActivityComponent by lazy {
можно удалить

2022-03-19 22:58 UTC, ZadorozhnyiSemen commented on app/src/main/java/ru/otus/daggerhomework/ViewModelProducer.kt
> +
Лишних пустых строчек лучше избегать, одной достаточно

2022-03-19 22:58 UTC, ZadorozhnyiSemen commented on app/src/main/java/ru/otus/daggerhomework/ViewModelProducer.kt
> +class ViewModelProducer (
По хорошему у конструктора вью модели должен быть @Inject перед конструктором, чтобы не создавать ее вручную

2022-03-19 22:58 UTC, ZadorozhnyiSemen commented on app/src/main/java/ru/otus/daggerhomework/ViewModelProducer.kt
> +class ViewModelProducerFactory(private val colorGenerator: ColorGenerator,private val context: Context,private val publishSubject: PublishSubject<Int>) :
Посмотри как делаются обобщенные ViewModelFactory для даггера, необязательно будет для каждой свою писать https://medium.com/@vit.onix/dagger2-viewmodel-81d4cd59f642

2022-03-19 22:58 UTC, ZadorozhnyiSemen commented on app/src/main/java/ru/otus/daggerhomework/di/ApplicationComponent.kt
> +
чоень много лишних строчек)

2022-03-20 05:48 UTC, quriza commented on app/src/main/java/ru/otus/daggerhomework/MainActivity.kt
> +       /* val observer = Observer<ViewModelProducer.Result> { result ->
+

2022-03-20 05:48 UTC, quriza commented on app/src/main/java/ru/otus/daggerhomework/MainActivity.kt
> +/*    val appMainActivityComponent: MainActivityComponent by lazy {
+

2022-03-20 05:49 UTC, quriza commented on app/src/main/java/ru/otus/daggerhomework/ViewModelProducer.kt
> +class ViewModelProducer (
это понятно, но в задаче не заказывали. А почему вообще поставлена задача пробрасывать контекст через фрагмент? Не проще сразу во вьюмодель заинжектить?

2022-03-20 13:24 UTC, quriza commented on app/src/main/java/ru/otus/daggerhomework/App.kt
> +    override fun onCreate() {
+

2022-03-20 13:24 UTC, quriza commented on app/src/main/java/ru/otus/daggerhomework/FragmentProducer.kt
> +class FragmentProducer @Inject constructor(context:Context,colorGenerator: ColorGenerator,publishSubject: PublishSubject<Int>) : Fragment() {
+ спасибо теперь точно не забуду

2022-03-20 13:27 UTC, quriza commented on app/src/main/java/ru/otus/daggerhomework/FragmentReceiver.kt
> +        viewModel.result.observe(viewLifecycleOwner, colorObserver)
+

2022-03-20 13:28 UTC, quriza commented on app/src/main/java/ru/otus/daggerhomework/ViewModelProducer.kt
> +class ViewModelProducerFactory(private val colorGenerator: ColorGenerator,private val context: Context,private val publishSubject: PublishSubject<Int>) :
+ спасибо за наводку

2025-04-09 11:34 UTC, closed without merging